# Generated by Django 5.2.15 on 2026-06-16 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='分类编码')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '规则分类',
                'verbose_name_plural': '规则分类',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=10, unique=True, verbose_name='规则ID')),
                ('name', models.CharField(max_length=200, verbose_name='规则名称')),
                ('description', models.TextField(blank=True, verbose_name='规则描述')),
                ('rule_type', models.CharField(choices=[('keyword', '关键词匹配'), ('timing', '时间检测'), ('ai', 'AI判断'), ('hybrid', '混合检测')], default='keyword', max_length=20, verbose_name='规则类型')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='规则参数')),
                ('first_penalty', models.IntegerField(default=20, verbose_name='首次扣分')),
                ('second_penalty', models.IntegerField(default=30, verbose_name='二次扣分')),
                ('third_penalty', models.IntegerField(default=40, verbose_name='三次扣分')),
                ('fourth_penalty', models.IntegerField(default=50, verbose_name='四次扣分')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='rules.rulecategory', verbose_name='规则分类')),
            ],
            options={
                'verbose_name': '质检规则',
                'verbose_name_plural': '质检规则',
            },
        ),
    ]
