# Generated by Django 5.2.15 on 2026-06-16 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '__first__'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待分析'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=10, verbose_name='状态')),
                ('attitude_score', models.IntegerField(blank=True, null=True, verbose_name='态度评分')),
                ('attitude_detail', models.JSONField(blank=True, default=dict, verbose_name='态度分析详情')),
                ('skill_score', models.IntegerField(blank=True, null=True, verbose_name='销售技巧评分')),
                ('skill_detail', models.JSONField(blank=True, default=dict, verbose_name='销售技巧分析详情')),
                ('suggestions', models.JSONField(blank=True, default=list, verbose_name='改进建议')),
                ('ai_suggestion_text', models.TextField(blank=True, verbose_name='AI建议文本')),
                ('raw_response', models.JSONField(blank=True, default=dict, verbose_name='原始响应')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_results', to='conversations.conversation', verbose_name='会话')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': 'AI分析结果',
                'verbose_name_plural': 'AI分析结果',
                'indexes': [models.Index(fields=['conversation', 'status'], name='ai_analysis_convers_64791c_idx')],
            },
        ),
    ]
