# Generated by Django 5.2.15 on 2026-06-16 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('taobao', '淘宝/天猫'), ('jd', '京东'), ('ali1688', '1688'), ('pdd', '拼多多'), ('yunke', '云客CRM')], max_length=20, verbose_name='平台')),
                ('conversation_id', models.CharField(max_length=200, verbose_name='会话ID')),
                ('shop_name', models.CharField(blank=True, max_length=200, verbose_name='店铺名称')),
                ('customer_name', models.CharField(blank=True, max_length=200, verbose_name='客户名称')),
                ('customer_id', models.CharField(blank=True, max_length=200, verbose_name='客户ID')),
                ('status', models.CharField(choices=[('unclosed', '未成交'), ('ordered', '已下单'), ('paid', '已付款'), ('closed', '已关闭')], default='unclosed', max_length=20, verbose_name='会话状态')),
                ('order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='订单金额')),
                ('has_inquiry', models.BooleanField(default=False, verbose_name='是否询价')),
                ('has_quote', models.BooleanField(default=False, verbose_name='是否报价')),
                ('has_ordered', models.BooleanField(default=False, verbose_name='是否下单')),
                ('has_paid', models.BooleanField(default=False, verbose_name='是否付款/锁单')),
                ('started_at', models.DateTimeField(verbose_name='会话开始时间')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='会话结束时间')),
                ('message_count', models.IntegerField(default=0, verbose_name='消息数量')),
                ('total_deduction', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='总扣分')),
                ('risk_level', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='low', max_length=10, verbose_name='风险等级')),
                ('ai_suggestion', models.TextField(blank=True, verbose_name='AI改进建议')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='原始数据')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='客服')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '会话',
                'verbose_name_plural': '会话',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('agent', '客服'), ('customer', '客户'), ('system', '系统')], max_length=10, verbose_name='发送方向')),
                ('sender_name', models.CharField(blank=True, max_length=200, verbose_name='发送者')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('sent_at', models.DateTimeField(verbose_name='发送时间')),
                ('reply_interval', models.FloatField(blank=True, null=True, verbose_name='回复间隔(分钟)')),
                ('is_ai_generated', models.BooleanField(default=False, verbose_name='是否AI生成')),
                ('msg_sequence', models.IntegerField(default=0, verbose_name='消息序号')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation', verbose_name='所属会话')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
                'ordering': ['conversation', 'sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['tenant', 'platform', 'started_at'], name='conversatio_tenant__01a9b8_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['tenant', 'employee'], name='conversatio_tenant__35f647_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['tenant', 'status'], name='conversatio_tenant__2898dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('tenant', 'platform', 'conversation_id')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'sent_at'], name='conversatio_convers_245fcd_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['tenant', 'direction'], name='conversatio_tenant__92ca90_idx'),
        ),
    ]
