# Generated by Django 5.2.15 on 2026-06-16 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('taobao', '淘宝/天猫'), ('jd', '京东'), ('ali1688', '1688'), ('pdd', '拼多多'), ('yunke', '云客CRM')], max_length=20, verbose_name='平台')),
                ('status', models.CharField(choices=[('running', '运行中'), ('success', '成功'), ('failed', '失败')], default='running', max_length=10, verbose_name='状态')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('conversations_pulled', models.IntegerField(default=0, verbose_name='拉取会话数')),
                ('messages_pulled', models.IntegerField(default=0, verbose_name='拉取消息数')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '同步日志',
                'verbose_name_plural': '同步日志',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ConnectorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('taobao', '淘宝/天猫'), ('jd', '京东'), ('ali1688', '1688'), ('pdd', '拼多多'), ('yunke', '云客CRM')], max_length=20, verbose_name='平台')),
                ('config_data', models.JSONField(default=dict, verbose_name='凭证配置(加密)')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connector_configs', to='tenants.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '平台连接配置',
                'verbose_name_plural': '平台连接配置',
                'unique_together': {('tenant', 'platform')},
            },
        ),
    ]
