# Generated by Django 5.2.15 on 2026-06-16 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='租户名称')),
                ('slug', models.SlugField(unique=True, verbose_name='标识')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('logo', models.ImageField(blank=True, upload_to='tenants/logos/', verbose_name='Logo')),
                ('primary_color', models.CharField(default='#409EFF', max_length=7, verbose_name='主题色')),
                ('timezone', models.CharField(default='Asia/Shanghai', max_length=50, verbose_name='时区')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '租户',
                'verbose_name_plural': '租户',
            },
        ),
        migrations.CreateModel(
            name='TenantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.CharField(max_length=100, verbose_name='配置键')),
                ('config_value', models.JSONField(verbose_name='配置值')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='tenants.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '租户配置',
                'verbose_name_plural': '租户配置',
                'unique_together': {('tenant', 'config_key')},
            },
        ),
    ]
