# Generated by Django 5.2.15 on 2026-06-16 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '__first__'),
        ('rules', '0001_initial_rules'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleTriggerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_content', models.TextField(blank=True, verbose_name='命中内容')),
                ('matched_keyword', models.CharField(blank=True, max_length=200, verbose_name='命中关键词')),
                ('evidence', models.JSONField(blank=True, default=dict, verbose_name='证据')),
                ('penalty', models.IntegerField(default=0, verbose_name='本次扣分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='触发时间')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_triggers', to='conversations.conversation', verbose_name='会话')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='客服')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.rule', verbose_name='规则')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '规则命中日志',
                'verbose_name_plural': '规则命中日志',
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('appealed', '已申述'), ('confirmed', '已确认'), ('closed', '已关闭')], default='pending', max_length=20, verbose_name='状态')),
                ('penalty_points', models.IntegerField(default=0, verbose_name='扣分')),
                ('adjusted_penalty', models.IntegerField(blank=True, null=True, verbose_name='调整后扣分')),
                ('evidence_text', models.TextField(blank=True, verbose_name='违规证据')),
                ('review_notes', models.TextField(blank=True, verbose_name='复核备注')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='复核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='conversations.conversation', verbose_name='会话')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='客服')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_violations', to=settings.AUTH_USER_MODEL, verbose_name='复核人')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.rule', verbose_name='规则')),
                ('rule_trigger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.ruletriggerlog', verbose_name='关联命中日志')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '违规单',
                'verbose_name_plural': '违规单',
            },
        ),
        migrations.AddIndex(
            model_name='ruletriggerlog',
            index=models.Index(fields=['conversation', 'rule'], name='reviews_rul_convers_e43709_idx'),
        ),
        migrations.AddIndex(
            model_name='ruletriggerlog',
            index=models.Index(fields=['tenant', 'employee'], name='reviews_rul_tenant__b419c9_idx'),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['tenant', 'status'], name='reviews_vio_tenant__4d5ca4_idx'),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['tenant', 'employee', 'status'], name='reviews_vio_tenant__88ee68_idx'),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['conversation', 'rule'], name='reviews_vio_convers_d45af2_idx'),
        ),
    ]
