# Generated by Django 5.2.15 on 2026-06-16 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='日报日期')),
                ('total_conversations', models.IntegerField(default=0, verbose_name='会话总数')),
                ('violation_count', models.IntegerField(default=0, verbose_name='违规数')),
                ('total_penalty', models.IntegerField(default=0, verbose_name='总扣分')),
                ('high_risk_count', models.IntegerField(default=0, verbose_name='高风险会话数')),
                ('avg_score', models.FloatField(default=100.0, verbose_name='平均分')),
                ('employee_rankings', models.JSONField(default=list, verbose_name='员工排名')),
                ('rule_distribution', models.JSONField(default=list, verbose_name='规则分布')),
                ('high_risk_sessions', models.JSONField(default=list, verbose_name='高风险会话')),
                ('status', models.CharField(choices=[('draft', '待推送'), ('sent', '已推送')], default='draft', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='tenants.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '日报',
                'verbose_name_plural': '日报',
                'ordering': ['-report_date'],
                'unique_together': {('tenant', 'report_date')},
            },
        ),
    ]
